---
title: "Getting started with sgpFlowMatrices"
author: "Damian W Betebenner"
date: "`r toOrdinal::toOrdinalDate()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started with sgpFlowMatrices}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r include = FALSE}
library(sgpFlowMatrices)
is_html_output = function() {
  knitr::opts_knit$get("rmarkdown.pandoc.to")=="html"
}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "",
    prompt=TRUE,
    fig.dpi = 96
			)
if (is_html_output()) {
    options(width=1000)
}
```

# Introduction

The R package **sgpFlowMatrices** contains sgpFlow coefficient matrices for use with the sgpFlow package in calculating percentile growth trajectories.
The package is under active development by staff at the [Center for Assessment](https://www.nciea.org).

# Contents

The baseline coefficient matrices embedded in **sgpFlowMatrices** are updated periodically. Current contents include:

* DEMO_sgpFlowMatrices: Contains single-cohort (2023-2024) and super-cohort (2020-2021 to 2023-2024) matrices DEMO based upon sgpDataLONG.

# Use of sgpFlowMatrices

After [installing](../index.html#installation) the package from GitHub, one conducts baseline SGP calculations with the matrices in this package.
Baseline matrices are added to the `SGPstateData` object embedded in the `SGP` prior to running `SGP` analyses supply the appropriate state abbreviation and year
to the `addMatrices` function. For example:

```
SGPstateData <- sgpFlowMatrices::addMatrices("DEMO", "SUPER_COHORT", "2023_2024")
```

# Examples

```
SGPstateData <- sgpFlowMatrices::addMatrices("DEMO", "Single-Cohort", add.matrices.to.which.state="DEMO")
```

# Contributions & Requests

If you have contributions of baseline matrices or a feature request for the **sgpFlowMatrices** package, don't hesitate to write or set
up an [issue on GitHub](https://github.com/CenterForAssessment/sgpFlowMatrices/issues).
